### ISSUE TITLE
HA doesn't work on war deployed on Wildfly10.1, JDK8-121

### ISSUE THREAD

**Issue by czetsuya** [HotswapProjects/HotswapAgent#192]
Hi,

I have a multi-maven war project structure like:
main-project
-ejb-proj
-war-proj

I have eclipse with jboss tools, wildfly, jdk8.

I have followed the setup guide for eclipse, downloaded and setup the latest HA and DCEVM. When I run wildfly I can see the log:

HOTSWAP AGENT: 12:05:43.414 INFO (org.hotswap.agent.HotswapAgent) - Loading Hotswap agent {1.1.0-SNAPSHOT} - unlimited runtime class redefinition.

But when I change some of my xhtml files, refresh my browser page, no matter how many times it doesn't get reflected. 

I've also disabled wildfly caching just in case. Auto-deployment is also disabled.

Any idea why?

**Comment by skybber** [comment]
Auto-deployment (publishing resources on change) should be enabled in eclipse. You can check modified .xhtml in wildfly deployment path if it is really deployed.

**Comment by czetsuya** [comment]
I have deployed the war using jboss tools add and remove resources feature. The files are deployed successfully in wildfly's deployment folder. But changing an xhtml file in eclipse package explorer doesn't update the same file in deployment. And nothing is updated in the browser. Did I need to configure something in hotswap-agent.properties? So far I only changed extraClasspath setting to add the maven modules.

**Comment by skybber** [comment]
HA uses `webappDir` for definition of external webApp directory. Wildfly is based od ModuleClassLoder, there is a plugin in HA but it doesn't solve `webappDir` yet. There are 2 possibilities how to solve it in Wildfly:

* use some external program for synchronization IDE's webappDir with Wildfly's deploument webappDir
* don't use war deployment

**Comment by rbertoncelj** [comment]
Are there any plans for `webappDir` support on WildFly?

I had a quick look into existing Tomcat plugin but could not invest enough time into it so far to really understand how to implement something similar for Undertow.

**Comment by czetsuya** [comment]
If you're using eclipse, this feature should already be supported with Oxygen.

**Comment by skybber** [comment]
WebappDir is really not supported by [https://github.com/HotswapProjects/HotswapAgent/tree/master/plugin/hotswap-agent-jbossmodules-plugin](jbossmodules-plugin) . Therefore resources modifications are not reflected in JBoss.

**Comment by skybber** [comment]
webappDir now supported on wildfly via undertow plugin
